name: dispatcher

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.9
  - pytorch=1.9
  - cudatoolkit
  - psutil

  - pip
  - pip:
      - fastapi[all]
      - uvicorn[standard]
